/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BillManager;

import CustomerManager.Customer;
import Exceptions.Exceptions;
import ProductManager.*;
import ProductManager.ProductTableModel;
import java.util.LinkedList;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultCellEditor;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Mr_Duc
 */
public class BillManager extends javax.swing.JPanel {

    EbillManager billManager = new EbillManager();
    BillTableModel billTableModel = new BillTableModel();

    /**
     * Creates new form BillManager
     */
    public BillManager() {

        initComponents();
        addCustomerToComboBox();
        loadEbillTable();
        loadBillInfo_ProductTable();
        loadBillInfo_EBillTable();
        loadEbillDetails_BillManagerPanel();

        quantity.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                try {
                    Integer.parseInt(quantity.getText());
                    if (Integer.parseInt(quantity.getText()) <= 0) {
                        JOptionPane.showMessageDialog(quantity.getRootPane(), "Invalid quantity", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                    Exceptions.PreceedQuantityException(JtableBillDetail.getValueAt(JtableBillDetail.getSelectedRow(), 0), quantity.getText(), choosenProducts);
                    btnTotal.setEnabled(true);
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(quantity.getRootPane(), "Quantity not numberic", "Error", JOptionPane.ERROR_MESSAGE);
                    SwingUtilities.invokeLater(new Runnable() {
                        @Override
                        public void run() {
                            quantity.setText("");
                        }
                    });
                } catch (Exceptions ex) {
                    JOptionPane.showMessageDialog(quantity.getRootPane(), ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                    SwingUtilities.invokeLater(new Runnable() {
                        @Override
                        public void run() {
                            quantity.setText("");
                        }
                    });
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {

            }

            @Override
            public void changedUpdate(DocumentEvent e) {

            }
        });
        btnSave.setEnabled(false);
        btnTotal.setEnabled(false);
        createTableEbillDetail();
        addCustomerToSearchComboBox();
        addCreatorToSearchComboBox();
        JTableEbillDetails_BillManagerPanel.removeColumn(JTableEbillDetails_BillManagerPanel.getColumnModel().getColumn(0));
    }

    List<CustomerManager.Customer> custList = billManager.loadCustomers();

    private void addCustomerToComboBox() {

        for (Customer customer : custList) {
            cbCustomerName.addItem(customer.getName());
        }
    }

    private void loadEbillTable() {
        billTableModel.addListToTheTable(billManager.loadEbill());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        JPanel_NewBill = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        cbCustomerName = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCustCode = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAddr = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        Jpanel_BillInfor = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        JTableEbill = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtBillInfo_Customer = new javax.swing.JTextField();
        txtBillInfo_Phone = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtBillInfo_Address = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        JtableBillDetail = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        JTableProduct = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnTotal = new javax.swing.JButton();
        txtBillInfo_TotalPrice = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        cbbSearchbyName = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbbSearchbyCreator = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        cbbFromPrice = new javax.swing.JComboBox();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        JtableEbill_BillManagerPanel = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        JTableEbillDetails_BillManagerPanel = new javax.swing.JTable();

        jMenuItem1.setText("<html><u>R</u>efresh</html>");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("<html><u>R</u>efresh</html>");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu2.add(jMenuItem2);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Customer Information"));

        cbCustomerName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbCustomerNameItemStateChanged(evt);
            }
        });

        jLabel1.setText("Choose Customer :");

        jLabel2.setText("Date :");

        jLabel3.setText("Customer Code :");

        jLabel4.setText("Customer Phone :");

        jLabel5.setText("Customer Address :");

        txtCustCode.setEditable(false);

        txtPhone.setEditable(false);

        txtAddr.setEditable(false);
        txtAddr.setColumns(20);
        txtAddr.setRows(5);
        jScrollPane2.setViewportView(txtAddr);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbCustomerName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                    .addComponent(txtCustCode)
                    .addComponent(txtPhone))
                .addContainerGap(144, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel3, jLabel4, jLabel5});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(txtCustCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Bill List"));

        jTable1.setModel(billTableModel);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
        );

        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanel_NewBillLayout = new javax.swing.GroupLayout(JPanel_NewBill);
        JPanel_NewBill.setLayout(JPanel_NewBillLayout);
        JPanel_NewBillLayout.setHorizontalGroup(
            JPanel_NewBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel_NewBillLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        JPanel_NewBillLayout.setVerticalGroup(
            JPanel_NewBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_NewBillLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("New Bill", JPanel_NewBill);

        Jpanel_BillInfor.setComponentPopupMenu(jPopupMenu2);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Bill List"));

        JTableEbill.setModel(billTableModelInBillInfoPanel);
        JTableEbill.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        JTableEbill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTableEbillMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(JTableEbill);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Bill Information"));

        jLabel6.setText("Customer :");

        jLabel7.setText("Phone :");

        jLabel8.setText("Address :");

        txtBillInfo_Customer.setEditable(false);

        txtBillInfo_Phone.setEditable(false);

        txtBillInfo_Address.setEditable(false);
        txtBillInfo_Address.setColumns(20);
        txtBillInfo_Address.setRows(5);
        jScrollPane6.setViewportView(txtBillInfo_Address);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBillInfo_Customer)
                    .addComponent(txtBillInfo_Phone)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtBillInfo_Customer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtBillInfo_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Bill Detail"));

        JtableBillDetail.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(JtableBillDetail);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("List product"));

        JTableProduct.setModel(productTableModel);
        jScrollPane4.setViewportView(JTableProduct);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
        );

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Remove.png"))); // NOI18N
        jButton2.setText("Remove");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        jButton4.setText("Add");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btnTotal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/calculate.png"))); // NOI18N
        btnTotal.setText("Total :");
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });

        txtBillInfo_TotalPrice.setEditable(false);

        javax.swing.GroupLayout Jpanel_BillInforLayout = new javax.swing.GroupLayout(Jpanel_BillInfor);
        Jpanel_BillInfor.setLayout(Jpanel_BillInforLayout);
        Jpanel_BillInforLayout.setHorizontalGroup(
            Jpanel_BillInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel_BillInforLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Jpanel_BillInforLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(btnTotal)
                .addGap(18, 18, 18)
                .addComponent(txtBillInfo_TotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addContainerGap())
        );
        Jpanel_BillInforLayout.setVerticalGroup(
            Jpanel_BillInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel_BillInforLayout.createSequentialGroup()
                .addGroup(Jpanel_BillInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Jpanel_BillInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel_BillInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(btnSave)
                        .addComponent(jButton4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel_BillInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnTotal)
                        .addComponent(txtBillInfo_TotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Bill Information", Jpanel_BillInfor);

        jPanel3.setComponentPopupMenu(jPopupMenu1);
        jPanel3.setPreferredSize(new java.awt.Dimension(966, 500));

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Search"));

        cbbSearchbyName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Please Choose!" }));
        cbbSearchbyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbSearchbyNameActionPerformed(evt);
            }
        });

        jLabel9.setText("Customer:");

        jLabel10.setText("Creator :");

        jLabel11.setText("Price :");

        cbbSearchbyCreator.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Please Choose!" }));
        cbbSearchbyCreator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbSearchbyCreatorActionPerformed(evt);
            }
        });

        jLabel12.setText("Time :");

        cbbFromPrice.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Please Choose!", "10000000-50000000", "50000000-100000000" }));
        cbbFromPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbFromPriceActionPerformed(evt);
            }
        });

        jDateChooser2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser2PropertyChange(evt);
            }
        });

        jLabel14.setText("To :");

        jDateChooser3.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser3PropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(29, 29, 29)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbbSearchbyName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbbSearchbyCreator, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbbFromPrice, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jPanel8Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel12, jLabel9});

        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbbSearchbyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(cbbSearchbyCreator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(cbbFromPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12)))))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Bill List"));

        jScrollPane8.setComponentPopupMenu(jPopupMenu1);

        JtableEbill_BillManagerPanel.setModel(billTableModel);
        JtableEbill_BillManagerPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JtableEbill_BillManagerPanelMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(JtableEbill_BillManagerPanel);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Bill Detail"));

        JTableEbillDetails_BillManagerPanel.setModel(ebillDetailTableModel_BillManagerPanel);
        jScrollPane7.setViewportView(JTableEbillDetails_BillManagerPanel);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Bill Manager", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbCustomerNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbCustomerNameItemStateChanged
        txtCustCode.setText(String.valueOf(custList.get(cbCustomerName.getSelectedIndex()).getCustomerCode()));
        txtPhone.setText(String.valueOf(custList.get(cbCustomerName.getSelectedIndex()).getTel()));
        txtAddr.setText(String.valueOf(custList.get(cbCustomerName.getSelectedIndex()).getAddr()));
    }//GEN-LAST:event_cbCustomerNameItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String userName = UserProfile.UserProfile.getUserName();
        String date = String.format("%1$tm-%1$td-%1$tY", jDateChooser1.getDate());
        EBill bill = new EBill(1, billManager.returnUserCode(userName), Integer.parseInt(txtCustCode.getText()), date, 0);
        billManager.addEbill(bill);
        loadEbillTable();
        loadBillInfo_EBillTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JTableEbillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableEbillMouseClicked
        txtBillInfo_Customer.setText(billTableModel.getValueAt(JTableEbill.getSelectedRow(), 1).toString());
        txtBillInfo_Phone.setText(billManager.returnCustomerByCode(BillTableModel.getEmplList().get(JTableEbill.getSelectedRow()).getCustomerCode()).getTel());
        txtBillInfo_Address.setText(billManager.returnCustomerByCode(BillTableModel.getEmplList().get(JTableEbill.getSelectedRow()).getCustomerCode()).getAddr());

    }//GEN-LAST:event_JTableEbillMouseClicked
    List<Product> choosenProducts = new LinkedList<>();
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            Exceptions.NoRowSelectedInTable(JTableEbill.getSelectedRow() != -1, "Choose a bill to add to first");
            Exceptions.NoRowSelectedInTable(JTableProduct.getSelectedRow() != -1, "Choose product to add to");
            Exceptions.ProductExistent(Integer.parseInt(JTableProduct.getValueAt(JTableProduct.getSelectedRow(), 0).toString()), choosenProducts);
            for (int rowIndex : JTableProduct.getSelectedRows()) {
                choosenProducts.add(ProductTableModel.getEmplList().get(rowIndex));
                Vector rowMedicineChoice = new Vector();
                rowMedicineChoice.addElement(ProductTableModel.getEmplList().get(rowIndex).getProduct_Code());  //0
                rowMedicineChoice.addElement(ProductTableModel.getEmplList().get(rowIndex).getProduct_Name());//1
                rowMedicineChoice.addElement(ProductTableModel.getEmplList().get(rowIndex).getProduct_Price());//
                TableColumn columnQuantity = JtableBillDetail.getColumnModel().getColumn(3);
                columnQuantity.setCellEditor(new DefaultCellEditor(quantity));
                ebillDetailTableModel.addRow(rowMedicineChoice);
            }

        } catch (Exceptions ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        try {
            int total = 0;
            for (int i = 0; i < JtableBillDetail.getRowCount(); i++) {
                total += Integer.parseInt(JtableBillDetail.getValueAt(i, 2).toString()) * Integer.parseInt(JtableBillDetail.getValueAt(i, 3).toString());
            }
            txtBillInfo_TotalPrice.setText(String.valueOf(total));
            btnSave.setEnabled(true);
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "Enter the quantity", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnTotalActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            Exceptions.NoRowSelectedInTable(JTableEbill.getSelectedRow() != -1, "Choose a bill to add to first");
            Exceptions.NoRowSelectedInTable(JTableProduct.getSelectedRow() != -1, "Choose product to add to");
            for (int i = 0; i < JtableBillDetail.getRowCount(); i++) {
                ebillDetailManager.addEbillDetails(new EbillDetail(Integer.parseInt(JtableBillDetail.getValueAt(i, 0).toString()), BillTableModelInBillInfoPanel.getEmplList().get(JTableEbill.getSelectedRow()).getEbillCode(), Integer.parseInt(JtableBillDetail.getValueAt(i, 3).toString())));
                productManager.updateProductAvailableAmount(choosenProducts.get(i).getProduct_AvailableAmount()- Integer.parseInt(JtableBillDetail.getValueAt(i, 3).toString()), Integer.parseInt(JtableBillDetail.getValueAt(i, 0).toString()));
            }
            billManager.updateEbillTotalPrice(Integer.parseInt(txtBillInfo_TotalPrice.getText()), Integer.parseInt(JTableEbill.getValueAt(JTableEbill.getSelectedRow(), 0).toString()));
            loadEbillTable();
            loadBillInfo_ProductTable();
            BillTableModelInBillInfoPanel.getEmplList().remove(JTableEbill.getSelectedRow());
            loadBillInfo_EBillTable();
            loadEbillDetails_BillManagerPanel();
            btnSave.setEnabled(false);
            clearBillInfoPanel();
        } catch (Exceptions ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try {
            Exceptions.NoRowSelectedInTable(JtableBillDetail.getSelectedRow() != -1, "No product to remove");
            for (int rowIndex : JtableBillDetail.getSelectedRows()) {
                ebillDetailTableModel.removeRow(rowIndex);
                choosenProducts.remove(rowIndex);
            }
        } catch (Exceptions ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbbSearchbyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbSearchbyNameActionPerformed
        billManager.searchEbillbyColumn(1, cbbSearchbyName.getSelectedItem().toString(), JtableEbill_BillManagerPanel, billTableModel);


    }//GEN-LAST:event_cbbSearchbyNameActionPerformed

    private void cbbSearchbyCreatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbSearchbyCreatorActionPerformed
        billManager.searchEbillbyColumn(2, cbbSearchbyCreator.getSelectedItem().toString(), JtableEbill_BillManagerPanel, billTableModel);// TODO add your handling code here:
    }//GEN-LAST:event_cbbSearchbyCreatorActionPerformed

    private void JtableEbill_BillManagerPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtableEbill_BillManagerPanelMouseClicked
        try {
            billManager.searchEbillbyColumn(0, JtableEbill_BillManagerPanel.getValueAt(JtableEbill_BillManagerPanel.getSelectedRow(), 0).toString(), JTableEbillDetails_BillManagerPanel, ebillDetailTableModel_BillManagerPanel);
        } catch (java.lang.IndexOutOfBoundsException e) {
        }

    }//GEN-LAST:event_JtableEbill_BillManagerPanelMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jDateChooser2.setDate(null);
        jDateChooser3.setDate(null);
        JtableEbill_BillManagerPanel.clearSelection();
        billManager.searchEbillbyColumn(0, " ", JTableEbillDetails_BillManagerPanel, ebillDetailTableModel_BillManagerPanel);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void cbbFromPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbFromPriceActionPerformed
        billManager.searchEbillbyPrice(cbbFromPrice.getSelectedItem().toString(), JtableEbill_BillManagerPanel, billTableModel);
    }//GEN-LAST:event_cbbFromPriceActionPerformed

    private void jDateChooser3PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser3PropertyChange
        try {
            Exceptions.DateRangeException(jDateChooser2.getDate(), jDateChooser3.getDate());
            billManager.searchEbillbyDate(jDateChooser2.getDate(), jDateChooser3.getDate(), JtableEbill_BillManagerPanel, billTableModel);
        } catch (Exceptions ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (NullPointerException ex) {
        }
    }//GEN-LAST:event_jDateChooser3PropertyChange

    private void jDateChooser2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser2PropertyChange
        try {
            Exceptions.DateRangeException(jDateChooser2.getDate(), jDateChooser3.getDate());
            billManager.searchEbillbyDate(jDateChooser2.getDate(), jDateChooser3.getDate(), JtableEbill_BillManagerPanel, billTableModel);
        } catch (Exceptions ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (NullPointerException ex) {
        }
    }//GEN-LAST:event_jDateChooser2PropertyChange

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        clearBillInfoPanel();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

//////////////////////////////////////////////BILL INFORMATION///////////////////////////////////////
    private ProductTableModel productTableModel = new ProductTableModel();
    //private BillDetailTableModel billDetailTableModel;
    private ProductManager productManager = new ProductManager();
    JTextField quantity = new JTextField();
    EbillDetailsManager ebillDetailManager = new EbillDetailsManager();
    BillTableModelInBillInfoPanel billTableModelInBillInfoPanel = new BillTableModelInBillInfoPanel();

    private void loadBillInfo_ProductTable() {
        productTableModel.addListToTheTable(productManager.loadProducts());
    }

    private void loadBillInfo_EBillTable() {
        billTableModelInBillInfoPanel.addListToTheTable(ebillDetailManager.loadEbill());
    }

    private void createTableEbillDetail() {
        ebillDetailTableModel.setNumRows(0);
        Vector columnMedicineChoice = new Vector();
        columnMedicineChoice.addElement("Product Code");
        columnMedicineChoice.addElement("Name");
        columnMedicineChoice.addElement("Price");
        columnMedicineChoice.addElement("Quantity");
        JtableBillDetail.setModel(ebillDetailTableModel);
        ebillDetailTableModel.setColumnIdentifiers(columnMedicineChoice);
    }

    private void loadEbillDetails_BillManagerPanel() {
        ebillDetailTableModel_BillManagerPanel.addListToTheTable(ebillDetailManager.loadEbillDetails());

    }
    DefaultTableModel ebillDetailTableModel = new DefaultTableModel();
    BillDetailTableModel_BillManagerPanel ebillDetailTableModel_BillManagerPanel = new BillDetailTableModel_BillManagerPanel();

    /////////////////////////////////////////////////////////////////////
    private void clearBillInfoPanel() {
        btnSave.setEnabled(false);
        btnTotal.setEnabled(false);
        txtBillInfo_Customer.setText("");
        txtBillInfo_Phone.setText("");
        txtBillInfo_Address.setText("");
        txtBillInfo_TotalPrice.setText("");
        JTableEbill.clearSelection();
        JtableBillDetail.clearSelection();
        for (int i = 0; i < ebillDetailTableModel.getRowCount(); i++) {
            ebillDetailTableModel.removeRow(i);
        }
        choosenProducts.clear();
        JTableProduct.clearSelection();
    }

    private void addCustomerToSearchComboBox() {

        for (Customer customer : custList) {
            cbbSearchbyName.addItem(customer.getName());
        }
    }

    private void addCreatorToSearchComboBox() {

        for (int code : billManager.loadUserCode()) {

            cbbSearchbyCreator.addItem(billManager.returnUserNameByuserCode(code));
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel_NewBill;
    private javax.swing.JTable JTableEbill;
    private javax.swing.JTable JTableEbillDetails_BillManagerPanel;
    private javax.swing.JTable JTableProduct;
    private javax.swing.JPanel Jpanel_BillInfor;
    private javax.swing.JTable JtableBillDetail;
    private javax.swing.JTable JtableEbill_BillManagerPanel;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnTotal;
    private javax.swing.JComboBox cbCustomerName;
    private javax.swing.JComboBox cbbFromPrice;
    private javax.swing.JComboBox cbbSearchbyCreator;
    private javax.swing.JComboBox cbbSearchbyName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea txtAddr;
    private javax.swing.JTextArea txtBillInfo_Address;
    private javax.swing.JTextField txtBillInfo_Customer;
    private javax.swing.JTextField txtBillInfo_Phone;
    private javax.swing.JTextField txtBillInfo_TotalPrice;
    private javax.swing.JTextField txtCustCode;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
